# Generated by Django 4.2.9 on 2025-11-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_consultationnote_consultationattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationattachment',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='consultationnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
