# Generated by Django 4.2.9 on 2025-11-12 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_consultationattachment_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='identification_extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('ci', 'CI'), ('passport', 'Pasaporte'), ('ci_extranjero', 'CI Extranjero')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='specializations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfessionalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='professional_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pages.professional')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='pages.professional')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('professional', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('website', 'Website'), ('phone', 'Teléfono'), ('email', 'Correo'), ('social', 'Redes Sociales')], max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='pages.professional')),
            ],
            options={
                'unique_together': {('professional', 'value')},
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='pages.professional')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('professional', 'date')},
            },
        ),
    ]
