# Generated by Django 4.2.9 on 2025-11-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_professional_biography_professional_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('attended', 'Atendida'), ('completed', 'Terminada'), ('no_show', 'No Atendida')], default='pending', max_length=20),
        ),
    ]
