# Generated by Django 4.2.9 on 2025-11-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultorio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='pages.consultorio'),
        ),
    ]
