# Generated by Django 4.2.9 on 2025-11-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_consultation_consultorio_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color (#RRGGBB) for calendar display', max_length=7),
        ),
    ]
