# Generated by Django 4.2.9 on 2025-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_patient_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('attended', 'Atendida'), ('completed', 'Terminada'), ('no_show', 'No Atendida'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
