# Generated by Django 4.2.9 on 2025-11-15 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_consultation_charge_alter_consultation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAIThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('context', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='gpt-4o-mini', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_threads', to='pages.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_threads', to='pages.professional')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('professional', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='PatientAIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pages.patientaithread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
