# Generated by Django on 2025-11-17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_patientaithread_context_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaimessage',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
    ]
