# Generated by Django 4.2.9 on 2026-05-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_specialty_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='pages.specialty'),
        ),
    ]
