# Generated by Django 4.2.9 on 2026-05-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_professional_specialties_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaithread',
            name='openai_conversation_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
