# Generated by Django 4.2.9 on 2026-06-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_patientaithread_vector_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='role',
            field=models.CharField(choices=[('psychologist', 'Psicólogo'), ('psychiatrist', 'Psiquiatra'), ('secretary', 'Secretaria')], max_length=20),
        ),
        migrations.CreateModel(
            name='EEGSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, default='', max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, choices=[('POSITIVE', 'Positivo'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negativo'), ('', 'Sin datos')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eeg_sessions', to='pages.patient')),
            ],
            options={
                'verbose_name': 'Sesión EEG',
                'verbose_name_plural': 'Sesiones EEG',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EEGReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('attention', models.IntegerField(blank=True, null=True)),
                ('meditation', models.IntegerField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('theta', models.FloatField(blank=True, null=True)),
                ('alpha', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('gamma', models.FloatField(blank=True, null=True)),
                ('emotion_label', models.CharField(blank=True, default='', max_length=20)),
                ('emotion_confidence', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='pages.eegsession')),
            ],
            options={
                'verbose_name': 'Lectura EEG',
                'verbose_name_plural': 'Lecturas EEG',
                'ordering': ['timestamp'],
            },
        ),
    ]
